<template>
  <div>
      <p>1024</p>
      <ol>
          <li v-for="list in msg" :key="list.name">
              {{list.name}}
              {{list.age}}
              {{list.addr}}
          </li>
      </ol>
      <h1></h1>
      <table style='border:solid 1px #add9c0;width:100%;heigh:300px;cellpadding:0;cellspacing:0;'>
          <thead>
              <tr>
                  <th>编号</th>
                  <th>分类</th>
              </tr>
          </thead>
          <tbody>
              <tr v-for="list in result" :key="list.id" style='border:solid 1px #add9c0'>
                  <td  style='white-space:nowrap;vertical-align:middle;text-align:center;height:35px;border:solid 1px #add9c0'>{{list.id}}</td>
                  <td  style='white-space:nowrap;vertical-align:middle;text-align:center;height:35px;border:solid 1px #add9c0'>{{list.catalog}}</td>
              </tr>
          </tbody>
      </table>
  </div>
</template>

<script>
  export default {
    name:"Demo4",
    data(){
        return{
            "msg":[
						{name:'张三1',age:'18',addr:'vue1'},
						{name:'张三2',age:'18',addr:'vue2'},
						{name:'张三3',age:'18',addr:'vue3'},
						{name:'张三4',age:'18',addr:'vue4'},
						{name:'张三5',age:'18',addr:'vue5'},
						{name:'张三6',age:'18',addr:'vue6'}
                    ],
            "resultcode":"200",
					"reason":"success",
					"result":[
						{
							"id":"242",
							"catalog":"中国文学"
						},
						{
							"id":"252",
							"catalog":"人物传记"
						},
						{
							"id":"244",
							"catalog":"儿童文学"
						},
						{
							"id":"248",
							"catalog":"历史"
						},
						{
							"id":"257",
							"catalog":"哲学"
						},
						{
							"id":"243",
							"catalog":"外国文学"
						},
						{
							"id":"247",
							"catalog":"小说"
						},
						{
							"id":"251",
							"catalog":"心灵鸡汤"
						},
						{
							"id":"253",
							"catalog":"心理学"
						},
						{
							"id":"250",
							"catalog":"成功励志"
						},
						{
							"id":"249",
							"catalog":"教育"
						},
						{
							"id":"245",
							"catalog":"散文"
						},
						{
							"id":"256",
							"catalog":"理财"
						},
						{
							"id":"254",
							"catalog":"管理"
						},
						{
							"id":"246",
							"catalog":"经典名著"
						},
						{
							"id":"255",
							"catalog":"经济"
						},
						{
							"id":"258",
							"catalog":"计算机"
						}
					],
					"error_code":0
        }
    }
  }
</script>